force-app/main/default/objects/Circuit__c/Circuit__c.object-meta.xml
<CustomObject>
    <label>Circuit</label>
    <nameField>
        <label>Circuit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Circuits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Circuit__c/fields/Circuit__c.field-meta.xml
<CustomField>
    <fullName>Circuit__c</fullName>
    <label>Circuit</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Circuit__c/fields/CircuitImgUrl__c.field-meta.xml
<CustomField>
    <fullName>CircuitImgUrl__c</fullName>
    <label>CircuitImgUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Circuit__c/fields/Laps__c.field-meta.xml
<CustomField>
    <fullName>Laps__c</fullName>
    <label>Laps</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/GrandPrix__c/GrandPrix__c.object-meta.xml
<CustomObject>
    <label>GrandPrix</label>
    <nameField>
        <label>GrandPrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GrandPrixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GrandPrix__c/fields/Circuit__c.field-meta.xml
<CustomField>
    <fullName>Circuit__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Circuit</label>
    <referenceTo>Circuit__c</referenceTo>
    <relationshipLabel>GrandPrixes</relationshipLabel>
    <relationshipName>GrandPrixes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GrandPrixController.cls
public with sharing class GrandPrixController {

    
    @AuraEnabled(cacheable=true)
    public static List<String> getAllGrandPrixes() {
        List<GrandPrix__c> grandPrixRecords = [
            SELECT Name
            FROM GrandPrix__c
            ORDER BY Date__c
        ];
        
        List<String> grandPrixes = new List<String>();
        
        for (GrandPrix__c grandPrix : grandPrixRecords) {
            grandPrixes.add(grandPrix.Name);
        }
        
        return grandPrixes;

    }

    @AuraEnabled
    public static GrandPrix__c getCircuitByGrandPrix(String grandPrix){
        try {

            GrandPrix__c circuitRecord = [
                SELECT Circuit__r.Name, Circuit__r.Laps__c, Circuit__r.CircuitImgUrl__c, Date__c
                FROM GrandPrix__c
                WHERE Name = :grandPrix
            ];

            return circuitRecord;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static String getGrandPrixByCurrentDate(){
        try {

            Date currentDate = Date.today();

            GrandPrix__c circuitRecord = [
                SELECT Circuit__r.Name, Circuit__r.Laps__c, Circuit__r.CircuitImgUrl__c, Date__c, Name
                FROM GrandPrix__c
                WHERE Date__c < :currentDate
                ORDER BY Date__c DESC
                LIMIT 1
            ];

            return circuitRecord.Name;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}