force-app/main/default/objects/Races__c/fields/RaceDate__c.field-meta.xml
<CustomField>
    <fullName>RaceDate__c</fullName>
    <label>RaceDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/RacesController.cls
public with sharing class RacesController {

    

    @AuraEnabled(cacheable=true)
    public static List<String> getAllRaces() {
        List<Races__c> raceRecords = [
            SELECT Name
            FROM Races__c
            ORDER BY raceDate__c
        ];
        
        List<String> raceNames = new List<String>();
        
        for (Races__c race : raceRecords) {
            raceNames.add(race.Name);
        }
        
        return raceNames;

    }



}