force-app/main/default/objects/Car__c/Car__c.object-meta.xml
<CustomObject>
    <label>Car</label>
    <nameField>
        <label>Naam van Car</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cars</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Car__c/fields/Chassis__c.field-meta.xml
<CustomField>
    <fullName>Chassis__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Chassis</label>
    <referenceTo>Chassis__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Car__c/fields/Engine__c.field-meta.xml
<CustomField>
    <fullName>Engine__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Engine</label>
    <referenceTo>Engine__c</referenceTo>
    <relationshipLabel>Cars</relationshipLabel>
    <relationshipName>Cars</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Chassis__c/Chassis__c.object-meta.xml
<CustomObject>
    <label>Chassis</label>
    <nameField>
        <label>Naam van Chassis</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chassis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Naam van Driver</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Engine__c/Engine__c.object-meta.xml
<CustomObject>
    <label>Engine</label>
    <nameField>
        <label>Naam van Engine</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Engines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <label>Profile</label>
    <nameField>
        <label>Naam van Profile</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Profiles</relationshipLabel>
    <relationshipName>Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Results__c/Results__c.object-meta.xml
<CustomObject>
    <label>Results</label>
    <nameField>
        <label>Results Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Results__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Results__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Naam van Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/CarOne__c.field-meta.xml
<CustomField>
    <fullName>CarOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CarOne</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/CarTwo__c.field-meta.xml
<CustomField>
    <fullName>CarTwo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CarTwo</label>
    <referenceTo>Car__c</referenceTo>
    <relationshipLabel>Teams (CarTwo)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Business/GameEngine.cls
public with sharing class GameEngine {

    public static String CalculateScore(String grandPrix) {

        // Get current Results
        List<Results__c> results = GrandPrixService.getResultsByGrandprix(grandPrix);

        // Get User Profile
        Profile__c profile = getUserProfile();

        String engineOne = profile.Team__r.CarOne__r.Engine__r.Name;
        String producerEngineOne = profile.Team__r.CarOne__r.Engine__r.Team__c;
        String engineTwo = profile.Team__r.CarTwo__r.Engine__r.Name;
        String producerEngineTwo = profile.Team__r.CarTwo__r.Engine__r.Team__c;


        
        // Calculate Engine Points
        String engineOneName = calculateEnginePoints(results, producerEngineOne, producerEngineTwo);

        return engineOneName;
    }

    public static List<Results__c> getGrandPrixResults(String grandPrix) {
        return GrandPrixService.getResultsByGrandprix(grandPrix);
    }

    public static Profile__c getUserProfile() {

        Id userId = UserInfo.getUserId();

        Profile__c profileRecord = [
            SELECT Id,
                Team__r.Name,
        
                Team__r.CarOne__r.Driver__r.Name, 
                Team__r.CarTwo__r.Driver__r.Name,
        
                Team__r.CarOne__r.Engine__r.Name,
                Team__r.CarOne__r.Engine__r.Team__c,
                Team__r.CarTwo__r.Engine__r.Name,
                Team__r.CarTwo__r.Engine__r.Team__c,
        
                Team__r.CarOne__r.Chassis__r.Name,
                Team__r.CarTwo__r.Chassis__r.Name
     
            FROM Profile__c
            WHERE UserId__c = :userId
        ];

        return profileRecord;
    } 

    public static List<Decimal> getPositions(List<Results__c> results, String team, String driver) {

        List<Decimal> positions = new List<Decimal>();

        for (Results__c result : results) {
            if(result.Team__c == team) {
                positions.add(result.position__c);
            }
        }

        return positions;

    }

    public static String calculateEnginePoints(List<Results__c> results, String producerEngineOne, String producerEngineTwo) {
        return producerEngineOne;
    }


}