force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Naam van Driver</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/Inventory__c.object-meta.xml
<CustomObject>
    <label>Inventory</label>
    <nameField>
        <label>Inventory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventorys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Inventorys</relationshipLabel>
    <relationshipName>Inventorys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Item_Type__c.field-meta.xml
<CustomField>
    <fullName>Item_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Driver</fullName>
            </value>
            <value>
                <fullName>Engine</fullName>
            </value>
            <value>
                <fullName>Chassis</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Inventory__c/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Profile</label>
    <referenceTo>Profile__c</referenceTo>
    <relationshipLabel>Inventorys</relationshipLabel>
    <relationshipName>Inventorys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Profile__c/Profile__c.object-meta.xml
<CustomObject>
    <label>Profile</label>
    <nameField>
        <label>Naam van Profile</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Profile__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>240</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/services/ShopService.cls
public with sharing class ShopService {

    public static Profile__c profile = getProfile();

    public static String buyDriver(String driverName){

        Decimal profileBalance = ShopService.profile.Balance__c;

        Driver__c driver = [SELECT Id, Price__c FROM Driver__c WHERE Name = :driverName];
        Decimal driverPrice = driver.Price__c;


        if (profileBalance >= driverPrice) {
            Inventory__c item_Driver = new Inventory__c();
            item_Driver.Driver__c = driver.Id;
            item_Driver.Profile__c = profile.Id;
            item_Driver.Item_Type__c = 'Driver';
            insert item_Driver;
            
            ShopService.updateProfileBalance(driverPrice.intValue());
        }


        return 'Je hebt Driver ';

    }

    public static Profile__c getProfile(){
        Id userId = UserInfo.getUserId();
        return [SELECT Id, Balance__c FROM Profile__c WHERE UserId__c = :userId];
    }



    public static void updateProfileBalance(Integer balance){

        ShopService.profile.Balance__c -= balance;
        update ShopService.profile;

    }

}