force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Naam van Driver</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rank__c/Rank__c.object-meta.xml
<CustomObject>
    <label>Ranking</label>
    <nameField>
        <label>Rank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rankings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Rank__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Rankings</relationshipLabel>
    <relationshipName>Rankings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Naam van Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/DriverOne__c.field-meta.xml
<CustomField>
    <fullName>DriverOne__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DriverOne</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Teams (DriverOne)</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/DriverTwo__c.field-meta.xml
<CustomField>
    <fullName>DriverTwo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>DriverTwo</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Teams (DriverTwo)</relationshipLabel>
    <relationshipName>Teams1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/fields/logoImgUrl__c.field-meta.xml
<CustomField>
    <fullName>logoImgUrl__c</fullName>
    <label>logoImgUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RankingController.cls
public with sharing class RankingController {


    @AuraEnabled(cacheable=true)
    public static List<Rank__c> getLastThreeRanks() {
        List<Rank__c> rankRecords = [
            SELECT Id, Rank__c, 
                Team__r.Id, Team__r.logoImgUrl__c, Team__r.Name, Team__r.DriverOne__r.Name, Team__r.DriverTwo__r.Name,
                Team__r.DriverOne__r.DriverImgUrl__c, Team__r.DriverTwo__r.DriverImgUrl__c
            FROM Rank__c
            ORDER BY Rank__c DESC
            LIMIT 3
        ];
            
        return rankRecords;
    }

}