force-app/main/default/objects/Driver__c/Driver__c.object-meta.xml
<CustomObject>
    <label>Driver</label>
    <nameField>
        <label>Naam van Driver</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Drivers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GrandPrix__c/GrandPrix__c.object-meta.xml
<CustomObject>
    <label>GrandPrix</label>
    <nameField>
        <label>GrandPrix Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GrandPrixes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GrandPrix__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Race</label>
    <referenceTo>Race__c</referenceTo>
    <relationshipLabel>GrandPrixes</relationshipLabel>
    <relationshipName>GrandPrixes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Race__c/Race__c.object-meta.xml
<CustomObject>
    <label>Race</label>
    <nameField>
        <label>Race Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Races</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Race__c/fields/Results__c.field-meta.xml
<CustomField>
    <fullName>Results__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Results</label>
    <referenceTo>Results__c</referenceTo>
    <relationshipLabel>Races</relationshipLabel>
    <relationshipName>Races</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Results__c/Results__c.object-meta.xml
<CustomObject>
    <label>Results</label>
    <nameField>
        <label>Results Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Results</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Results__c/fields/ApiRaceId__c.field-meta.xml
<CustomField>
    <fullName>ApiRaceId__c</fullName>
    <label>ApiRaceId</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Results__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <label>Driver</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Results__c/fields/Grid__c.field-meta.xml
<CustomField>
    <fullName>Grid__c</fullName>
    <label>Grid</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Results__c/fields/Pits__c.field-meta.xml
<CustomField>
    <fullName>Pits__c</fullName>
    <label>Pits</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Results__c/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Results</relationshipLabel>
    <relationshipName>Results</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Naam van Team</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/Driver__c.field-meta.xml
<CustomField>
    <fullName>Driver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Driver</label>
    <referenceTo>Driver__c</referenceTo>
    <relationshipLabel>Teams</relationshipLabel>
    <relationshipName>Teams</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GrandPrixService.cls
public with sharing class GrandPrixService {

    public static List<Results__c> getResultsByGrandprix(String grandPrix){
        try {

            GrandPrix__c apiRaceIdRecord = [
                SELECT Id, Race__r.ApiRaceId__c
                FROM GrandPrix__c
                WHERE Name = 'Saudi Arabian Grand Prix'
                LIMIT 1
            ];

            Decimal apiRaceId = apiRaceIdRecord.Race__r.ApiRaceId__c;

            List<Results__c> results = [
                SELECT Id, Driver__c, Grid__c, Laps__c, Pits__c, Points__c, Position__c, Team__c, Time__c
                FROM Results__c
                WHERE ApiRaceId__c = :apiRaceId
                ORDER BY Position__c ASC
            ];

            return results;


        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}