force-app/main/default/objects/Achievement__c/Achievement__c.object-meta.xml
<CustomObject>
    <label>Achievement</label>
    <nameField>
        <label>Achievement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Achievements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Achievement__c/fields/AchievementImgUrl__c.field-meta.xml
<CustomField>
    <fullName>AchievementImgUrl__c</fullName>
    <label>AchievementImgUrl</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Business/ScoreSystem.cls
public with sharing class ScoreSystem {


    public static Score positionPoints(List<Decimal> positions, String category) {

        Integer total = 0; 
        String achievementName = category + '_Position';

        for (Decimal position : positions) {
            Integer points = RankingScore.getPointsByPosition(position.intValue());
            total += points;
        }

        Achievement__c icon = [SELECT achievementImgUrl__c FROM Achievement__c WHERE Name = :achievementName];

        Score score = new Score( category + ' Points', total, category, icon.achievementImgUrl__c);
        
        return score;
    }

}